serenity {
  project.name = "InvSystem - Pruebas de Login"
  take.screenshots = AFTER_EACH_STEP
  maintain.session.for.scenarios = false
}

webdriver {
  driver = chrome
  base.url = "http://localhost:4200"
  timeouts {
    implicit.wait = 5000
    action = 5000
  }
}

# Opciones de Chrome para WSL (headless + sin sandbox)
chrome.switches = "--no-sandbox,--headless=new,--disable-gpu,--disable-dev-shm-usage,--window-size=1920,1080,--remote-allow-origins=*,--use-gl=swiftshader,--disable-gpu-sandbox,--disable-software-rasterizer"
